remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
title: "EJ Rojas" 
title_separator: "|"
description: "A flexible Jekyll theme project used as my teamtreehouse.com project."
include: ["_pages"]
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/

author:
  name   : "EJ Rojas"
  avatar : "/assets/images/portrait_2.jpg"
  bio    : "I am a coffee aficionado with a growth mind set learning web development and java app development. Currently taking computer science and having fun coding!!!"
  email  : "studiojava.ca@gmail.com"
  uri    : "https://github.com/StudioJava"
  instagram: "javastudio.ca"
  


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true