remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
title: "EJ Rojas" 
title_separator: "|"
description: "A flexible Jekyll theme project used as my teamtreehouse.com project."
include: ["_pages"]